### ISSUE TITLE
회의록페이지 작업

### ISSUE THREAD

**Issue by sooje0ng** [OSSProj-OpenMind/OpenMind-Frontend#16]
## IssueName
> 회의록 페이지를 작업합니다.

## Description
> 이슈에 대한 간단한 설명을 작성해주세요.

## Todo
- [x] 회의록 제목 input 추가
- [x] 회의록 조회 UI생성
- [x] 회의록 api 라우팅
- [x] 파일 upload 알아보기
